version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-jessie
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: deploy to S3
          command: aws s3 sync build s3://${ONGAQJS_ASSET__S3}/ --acl public-read --delete
      - run:
          name: purge cache
          command: aws cloudfront create-invalidation --distribution-id ${ONGAQJS_ASSET__CLOUDFRONT} --paths "/*"
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: settings
          filters:
            branches:
              only: master
