version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6-jessie
    working_directory: ~/build
    environment:
      - AWS_S3_BUCKET_NAME: asset.ongaqjs.com
      - CF_DIST_ID: E2Q2YOYAC5KTPH
    steps:
      - checkout
      - run: sudo pip install awscli
      - run:
          name: Deploy to S3 if branch is master.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build s3://${AWS_S3_BUCKET_NAME}/ --exact-timestamps --delete
            fi
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
            fi
