import ROOT from "./ROOT"
import SCHEME from "./SCHEME"
import ENDPOINT from "./ENDPOINT"

const ONGAQ_CONSTANTS = {
    ROOT, SCHEME, ENDPOINT
}

window.ONGAQ_CONSTANTS = window.ONGAQ_CONSTANTS || ONGAQ_CONSTANTS

export default ONGAQ_CONSTANTS