import ROOT from "./ROOT"
import SCHEME from "./SCHEME"
import SOUND_NAME from "./SOUND_NAME"
import ENDPOINT from "./ENDPOINT"

const ONGAQ_CONSTANTS = {
    ROOT, SCHEME, SOUND_NAME, ENDPOINT
}

window.ONGAQ_CONSTANTS = window.ONGAQ_CONSTANTS || ONGAQ_CONSTANTS

export default ONGAQ_CONSTANTS